### PR TITLE
Feat/mapping cleanup

### LINKED ISSUE #54: Make sure map tiles display in correct order

### LINKED ISSUE #56: Add Mapbox styling script tag

### LINKED ISSUE #57: Mapbox layer for point

### LINKED ISSUE #58: mapbox point popup

### PR DESCRIPTION
**Pull request by rmcchesn**
Correctly render tiles
Constrain map to window
Display locations from sample data.
Display icons for thumbs up and down based on rating
display popup with name and photo for each location.
Integrate search feature

closes #54, closes #56, closes #57, closes #58

### CODE REVIEW

**Comment by Andrew-Heath** [comment]
We're going to need the Map moved from the 'components' folder to a different one.  I believe it will be in 'containers' but we will have to double check with Derek.

**Comment by rmcchesn** [comment]
Not a problem. Let me know if you want anything moved from my end and I'll update or if its easier to merge first and do with your updates. Ether way.

**Comment by Andrew-Heath** [comment]
It might be better to do mine then yours, as mine will keep it where it was originally, then yours will move it to where Derek will place it.  We'll just have to make sure with my next merge (redux stuff) and Derek's to not have it all go kaput.

**Comment by rmcchesn** [comment]
Okay sounds good. I'll keep an eye for Derek to merge your pull request. Just let me know what folder you ultimately decide on and I'll update my pull request accordingly

**Comment by alexcstark** [comment]
What are we waiting on to merge this request?

**Comment by Andrew-Heath** [comment]
He needs to rebase to handle the conflicts.

**Pull request closed without merging**
